version: '3.1'

services:
  backend:
    image: ai_voice_change_server:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    restart: unless-stopped
    volumes:
      - /home/natas/pool1/ai/models/sovits/20221014:/code/pth:ro
    ports:
      - 6842:6842
